# Generated by Django 2.2.4 on 2019-08-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('CPF', models.IntegerField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.CharField(max_length=12)),
                ('bio', models.TextField(max_length=100)),
            ],
        ),
    ]
